### PR TITLE
First pass at building `os` with Meson

### PR DESCRIPTION
**Pull request by llasram**
Builds where everything is custom definitely cut against what Meson does best, but this still isn't too bad.  

The PR looks massive because the commit fixes the permissions of most of the files.  I'm happy to pull that commit out into a separate PR if it would make things easier.

### CODE REVIEW

**Comment by llasram** [comment]
(I forced-pushed because as I soon as I opened the PR I noticed that I'd messed up the `meson` command in `BUILDING`; I'll add any further changes as separate fixup commits and squash before you merge.)

**Comment by jdykstra** [comment]
I should have said this on the other PR's too, but nice work and thank you!  

Note that I don't think I ever got a system build from this project to successfully run on the VM.  Or maybe it wouldn't run on my real hardware.  Either way, there seemed to be a mismatch between the pcode ops generated by the compiler and the pcode interpreter.  That's why on the GitHub repository comment I didn't claim that this one was maintained.  Some winter I'll unscramble that...

**Comment by llasram** [comment]
No problem!  Glad to help out, and to have learned about Meson!

The cross-built images work fine for me under `ucsdpsys_vm`, both as built under the old build system and with Meson.  I haven't tried to see if they could be convinced to work with another p-machine interpreter on real (well, real-emulated) hardware.  I wonder if any 6502 sources have turned up since Peter Miller assembled what's available here?

**Comment by jdykstra** [comment]
I’m running on real hardware—a Z80-based machine I designed and constructed in 1979.  Everything I’ve built on Peter Miller’s cross-compiler has run fine on that except the OS itself.  The p-code interpreter is derived from the UCSD II.0 release.

The 6502 p-code interpreter was Apple-proprietary and not included in any of the releases from UCSD and Softtech Microsystems.  I’ve never seen a copy.

**Comment by llasram** [comment]
Oh!  That's awesome!  I see that the OS `arch/z80/interpreter/` sources are for I.5 -- do have more recent sources, or is this a contemporary binary II.0 build?

**Comment by jdykstra** [comment]
> Oh! That's awesome! I see that the OS arch/z80/interpreter/ sources are for I.5 -- do have more recent sources, or is this a contemporary binary II.0 build?

I’ve got the complete II.0 sources, from 1970’s 8-inch floppies.  I’m pretty sure that the same files are floating around the Web.  UCSD publicly released the I.5 sources;  the legal status of the II.0 files is much murkier.

**Pull request merged**
